enum LogType {
	// Actions
	CREATE_ACTION = "CREATE_ACTION",
	DELETE_ACTION = "DELETE_ACTION",
	DELETE_ACTIONS_BULK = "DELETE_ACTIONS_BULK",

	// Moderators
	CREATE_MODERATOR = "CREATE_MODERATOR",
	DELETE_MODERATOR = "DELETE_MODERATOR",
	UPDATE_MODERATOR = "UPDATE_MODERATOR",
	LINK_MODERATOR_ACCOUNT = "LINK_MODERATOR_ACCOUNT",
	UNLINK_MODERATOR_ACCOUNT = "UNLINK_MODERATOR_ACCOUNT",

	// Reports
	ACCEPT_REPORT = "ACCEPT_REPORT",
	DECLINE_REPORT = "DECLINE_REPORT",
}

export default LogType