enum RobloxThumbnailType {
	AVATAR = "Avatar",
	AVATAR_HEADSHOT = "AvatarHeadShot",
	GAME_ICON = "GameIcon",
	BADGE_ICON = "BadgeIcon",
	GAME_THUMBNAIL = "GameThumbnail",
	GAMEPASS = "GamePass",
	ASSET = "Asset",
	BUNDLE_THUMBNAIL = "BundleThumbnail",
	OUTFIT = "Outfit",
	GROUP_ICON = "GroupIcon",
	DEVELOPER_PRODUCT = "DeveloperProduct",
	AVATAR_BUST = "AvatarBust",
	AUTO_GENERATED_ASSET = "AutoGeneratedAsset",
	PLACE_ICON = "PlaceIcon",
}

export default RobloxThumbnailType