name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      
      - name: Authenticate with registry
        run: doctl registry login --expiry-seconds 120
      
      - name: Build
        run: docker build -t moderation-api .
      
      - name: Upload
        run: |
          docker tag moderation-api registry.digitalocean.com/free-draw/moderation-api:latest
          docker push registry.digitalocean.com/free-draw/moderation-api:latest

      - name: Download cluster configuration
        run: doctl kubernetes cluster kubeconfig save $CLUSTER_ID
        env:
          CLUSTER_ID: ${{ secrets.CLUSTER_ID }}
      
      - name: Apply latest deployment
        run: kubectl apply -f https://raw.githubusercontent.com/free-draw/moderation-deployment/main/deployment/frontend/api.yml
      
      - name: Rollout deployment
        run: kubectl rollout restart deployment/api --namespace moderation